# Generated by Django 6.0.6 on 2026-06-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo_placeholder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
