# Generated by Django 6.0.6 on 2026-06-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ficha_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
